ForestrySystem/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ForestrySystem.Data;
using ForestrySystem.Models;
using ForestrySystem.Services;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace ForestrySystem.Controllers
{
	[Route("event")]
	public class EventsController : Controller
	{
		private readonly ApplicationDbContext _context;
		private readonly EventsService _eventsService;
		public EventsController(ApplicationDbContext context, EventsService eventsService)
		{
			_context = context;
			_eventsService = eventsService;
		}

		// GET: Events
		public async Task<IActionResult> Index(string SearchString)
		{
			ViewData["CurrentFilter"] = SearchString;
			IQueryable<Events> events = _eventsService.GetEvents();
			if (!String.IsNullOrEmpty(SearchString))
			{
				events = _eventsService.GetFilteredEvents(SearchString, events);
			}
			return View(events);
		}

		

		[Route("findall")]
		public async Task<IActionResult> FindAllEvents()
		{
			var events = _context.Events.Select(e => new
			{
				id = e.Id,
				name = e.Name,
				date = e.Date.ToString("dd/MM/yyyy"),
				status = e.Status,
				purpose = e.Purpose,
				institution = e.Institutions,
			}).ToList();
			return new JsonResult(events);
		}

        // GET: Events/Details/5
        [Route("details")]
        public async Task<IActionResult> Details(int? id)
		{
			if (id == null || _context.Events == null)
			{
				return NotFound();
			}

			Events? events = await _eventsService.GetEvent(id);
			if (events == null)
			{
				return NotFound();
			}

			return View(events);
		}



		// GET: Events/Create
		[Authorize(Roles = "Expert,Admin")]
		[HttpGet]
        [Route("create")]
        public IActionResult Create()
		{
			return View();
		}

		// POST: Events/Create
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
        [Route("create")]
        public async Task<IActionResult> Create([Bind("Id,Name,Date,Status,Purpose,FIEventRefID")] Events events)
		{
			if (ModelState.IsValid)
			{
				await _eventsService.CreateEvent(events);
				return RedirectToAction(nameof(Index));
			}
			return View(events);
		}



		// GET: Events/Edit/5
		[Authorize(Roles = "Expert,Admin")]
		[HttpGet]
        [Route("edit")]
        public async Task<IActionResult> Edit(int? id)
		{
			if (id == null || _context.Events == null)
			{
				return NotFound();
			}

			var events = await _eventsService.GetEvent(id);
			if (events == null)
			{
				return NotFound();
			}
			return View(events);
		}

		// POST: Events/Edit/5
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		[Authorize(Roles = "Expert,Admin")]
        [Route("edit")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Date,Status,Purpose,FIEventRefID")] Events events)
		{
			if (id != events.Id)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				try
				{
					await _eventsService.UpdateEvent(events);
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!_eventsService.EventsExists(events.Id))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction(nameof(Index));
			}
			return View(events);
		}



		// GET: Events/Delete/5
		[Authorize(Roles = "Expert,Admin")]
		[HttpGet]
        [Route("delete")]
        public async Task<IActionResult> Delete(int? id)
		{
			if (id == null || _context.Events == null)
			{
				return NotFound();
			}

			var events = _eventsService.GetEvent(id);
			if (events == null)
			{
				return NotFound();
			}

			return View(events);
		}

		// POST: Events/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
        [Route("delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
		{
			if (_context.Events == null)
			{
				return Problem("Entity set 'ApplicationDbContext.Events'  is null.");
			}
			await _eventsService.DeleteEvent(id);
			return RedirectToAction(nameof(Index));
		}


	}
}

ForestrySystem/Controllers/TypeOfTimbersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ForestrySystem.Data;
using ForestrySystem.Models;
using Microsoft.AspNetCore.Authorization;
using System.Data;
using Microsoft.Data.SqlClient;
using ForestrySystem.Services;

namespace ForestrySystem.Controllers
{

	public class TypeOfTimbersController : Controller
	{
		private readonly ApplicationDbContext _context;
		private readonly TypeOfTimbersService _typeOfTimbersService;


		public TypeOfTimbersController(ApplicationDbContext context, TypeOfTimbersService typeOfTimbersService)
		{
			_context = context;
			_typeOfTimbersService = typeOfTimbersService;
		}

		// GET: TypeOfTimbers
		public async Task<IActionResult> Index(string SearchString, string sortOrder)
        {
            ViewData["CurrentFilter"] = SearchString;
            IQueryable<TypeOfTimber> types = _typeOfTimbersService.GetTypeOfTimbers();
            if (!String.IsNullOrEmpty(SearchString))
            {
                types = _typeOfTimbersService.GetFilteredTypeOfTimbers(SearchString, types);
            }
            return View(types);
        }




        // GET: TypeOfTimbers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.TypeOfTimber == null)
            {
                return NotFound();
            }

            TypeOfTimber? typeOfTimber = await _typeOfTimbersService.GetTypeOfTimber(id);
            if (typeOfTimber == null)
            {
                return NotFound();
            }

            return View(typeOfTimber);
        }

        

        // GET: TypeOfTimbers/Create
        [Authorize(Roles = "Expert,Admin")]
		public IActionResult Create()
		{
			return View();
		}

		// POST: TypeOfTimbers/Create
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([Bind("Id,TimberName,AmountForLogging,YearOfLogging")] TypeOfTimber typeOfTimber)
		{
			if (ModelState.IsValid)
            {
                await _typeOfTimbersService.CreateTypeOfTimber(typeOfTimber);
                return RedirectToAction(nameof(Index));
            }
            return View(typeOfTimber);
		}

        

        // GET: TypeOfTimbers/Edit/5
        [Authorize(Roles = "Expert,Admin")]
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null || _context.TypeOfTimber == null)
			{
				return NotFound();
			}

			var typeOfTimber = await _typeOfTimbersService.GetTypeOfTimber(id);
			if (typeOfTimber == null)
			{
				return NotFound();
			}
			return View(typeOfTimber);
		}

		// POST: TypeOfTimbers/Edit/5
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int id, [Bind("Id,TimberName,AmountForLogging,YearOfLogging")] TypeOfTimber typeOfTimber)
		{
			if (id != typeOfTimber.Id)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				try
                {
                    await _typeOfTimbersService.UpdateTypeOfTimber(typeOfTimber);
                }
                catch (DbUpdateConcurrencyException)
				{
					if (!_typeOfTimbersService.TypeOfTimberExists(typeOfTimber.Id))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction(nameof(Index));
			}
			return View(typeOfTimber);
		}

        

        // GET: TypeOfTimbers/Delete/5
        [Authorize(Roles = "Expert,Admin")]
		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null || _context.TypeOfTimber == null)
			{
				return NotFound();
			}

			var typeOfTimber = await _typeOfTimbersService.GetTypeOfTimber(id);
			if (typeOfTimber == null)
			{
				return NotFound();
			}

			return View(typeOfTimber);
		}

		// POST: TypeOfTimbers/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.TypeOfTimber == null)
            {
                return Problem("Entity set 'ApplicationDbContext.TypeOfTimber'  is null.");
            }
            await _typeOfTimbersService.RemoveTypeOfTimber(id);
            return RedirectToAction(nameof(Index));
        }

        
	}
}

ForestrySystem/Controllers/TypeOfWoodsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ForestrySystem.Data;
using ForestrySystem.Models;
using Microsoft.AspNetCore.Authorization;
using System.Data;
using Microsoft.Data.SqlClient;
using ForestrySystem.Services;

namespace ForestrySystem.Controllers
{

	public class TypeOfWoodsController : Controller
	{
		private readonly TypeOfWoodsService _typeOfWoodService;
		private ApplicationDbContext _context;
        private readonly ImagesService _imgService;
        public TypeOfWoodsController(TypeOfWoodsService typeOfWoodService, ApplicationDbContext context, ImagesService imgService)
		{
			_typeOfWoodService = typeOfWoodService;
			_context = context;
			this._imgService = imgService;
		}

		// GET: TypeOfWoods
		public async Task<IActionResult> Index(string SearchString, string sortOrder)
		{
            ViewData["CurrentFilter"] = SearchString;
            IQueryable<TypeOfWood> types = _typeOfWoodService.GetTypeOfWood();
            if (!String.IsNullOrEmpty(SearchString))
            {
                types = _typeOfWoodService.GetFilteredTypeOfWood(SearchString, types);
            }
            return View(types);
		}

		// GET: TypeOfWoods/Details/5

		public async Task<IActionResult> Details(int id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var typeOfWood = await _typeOfWoodService.GetTypeOfWoodById(id);
			if (typeOfWood == null)
			{
				return NotFound();
			}

			return View(typeOfWood);
		}

		// GET: TypeOfWoods/Create
		[Authorize(Roles = "Expert,Admin")]
		public IActionResult Create() => View();

		// POST: TypeOfWoods/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Create([Bind("Id,SpeciesName,Origin,AmountForLogging,YearOfLogging")] TypeOfWood typeOfWood)
		{
			if (ModelState.IsValid)
			{
				//_context.Add(typeOfWood);
				//await _context.SaveChangesAsync();
				return RedirectToAction(nameof(Index));
			}
			// ako vsichko e minalo uspeshno vrushame true ako bugva false 
			return View(typeOfWood);
		}

		// GET: TypeOfWoods/Edit/5
		[Authorize(Roles = "Expert,Admin")]
		public async Task<IActionResult> Edit(int id)
		{
			if (id == null || _context.WoodTypes == null)
			{
				return NotFound();
			}
			//transfer to service
			var typeOfWood = await _typeOfWoodService.GetTypeOfWoodById(id);
			if (typeOfWood == null)
			{
				return NotFound();
			}
			return View(typeOfWood);
		}

		// POST: TypeOfWoods/Edit/5
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int id, [Bind("Id,SpeciesName,Origin,AmountForLogging,YearOfLogging")] TypeOfWood typeOfWood)
		{
			if (id != typeOfWood.Id)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				try
                {
                    //proverqvame dali go ima ako ima null vrushtame greshka 
                    await _typeOfWoodService.UpdateTypeOfWood(typeOfWood);
                    //tuk izvikvame service
                }
                catch (DbUpdateConcurrencyException)
				{
					if (!_typeOfWoodService.TypeOfWoodExists(typeOfWood.Id))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction(nameof(Index));
			}
			return View(typeOfWood);
		}

        

        // GET: TypeOfWoods/Delete/5
        [Authorize(Roles = "Expert,Admin")]
		public async Task<IActionResult> Delete(int id)
		{
			if (id == null || _context.WoodTypes == null)
			{
				return NotFound();
			}

			var typeOfWood = await _typeOfWoodService.GetTypeOfWoodById(id);

			if (typeOfWood == null)
			{
				return NotFound();
			}

			return View(typeOfWood);
		}

		// POST: TypeOfWoods/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.WoodTypes == null)
            {
                return Problem("Entity set 'ApplicationDbContext.WoodTypes'  is null.");
            }
            //namirame po ID
            await _typeOfWoodService.DeleteTypeOfWood(id);
            return RedirectToAction(nameof(Index));
        }
        [HttpPost]
        public IActionResult AddImage(IFormFile file)
        {
            _imgService.UploadFileAsync(file).Wait();
            return RedirectToAction(nameof(Index));
        }


    }
}

ForestrySystem/Controllers/UserRolesController.cs
using ForestrySystem.Data;
using ForestrySystem.Models;
using ForestrySystem.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data;

namespace ForestrySystem.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UserRolesController : Controller
    {
        private ApplicationDbContext _context;
        private readonly UserManager<AppUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserRolesService _userRolesService;
        //constructor dependency injection
        public UserRolesController(UserRolesService userRolesService, ApplicationDbContext context, UserManager<AppUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
            _context = context;
            _userRolesService = userRolesService;
        }
        public async Task<IActionResult> Index()
        {
            var users = await _userRolesService.GetUsersAsync();
            var userRolesViewModel = new List<UserRolesViewModel>();
            foreach (AppUser user in users)
            {
                var thisViewModel = new UserRolesViewModel();
                thisViewModel.UserId = user.Id;
                thisViewModel.Email = user.Email;
                thisViewModel.FirstName = user.firstName;
                thisViewModel.LastName = user.lastName;
                thisViewModel.Roles = await _userRolesService.GetUserRolesAsync(user);
                userRolesViewModel.Add(thisViewModel);
            }
            return View(userRolesViewModel);
        }


        public async Task<IActionResult> Manage(string userId)
        {
            ViewBag.userId = userId;
            AppUser user = await _userRolesService.GetUser(userId);
            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {userId} cannot be found";
                return View("NotFound");
            }
            ViewBag.UserName = user.UserName;
            List<ManageUserRolesViewModel> model = await _userRolesService.GenerateViewModel(user);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Manage(List<ManageUserRolesViewModel> model, string userId)
        {
            var user = await _userRolesService.GetUser(userId);
            if (user == null)
            {
                return View();
            }
            IdentityResult result = await _userRolesService.RemoveRole(user);
            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Cannot remove user existing roles");
                return View(model);
            }
            result = await _userManager.AddToRolesAsync(user, model.Where(x => x.Selected).Select(y => y.RoleName));
            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Cannot add selected roles to user");
                return View(model);
            }
            return RedirectToAction("Index");
        }



        public async Task<IActionResult> Delete(List<ManageUserRolesViewModel> model, string Id)
        {
            var UserToDelete = await _userRolesService.GetUser(Id);

            if (UserToDelete != null)
            {
                IdentityResult result = await _userRolesService.DeleteUser(UserToDelete);
                if (result.Succeeded)
                {
                    return View(model);
                }
            }
            return RedirectToAction("Index");
        }

    }
}

ForestrySystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ForestrySystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ForestrySystem.styles.css" asp-append-version="true" />
</head>

<header>
    <nav class="fill navbar navbar-expand-sm navbar-toggleable-sm navbar-light box-shadow">
        <div class="container-fluid">
            <img src="~/images/logo.jpg" alt="Logo Image" style="width:300px;height:70px;">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Начало</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="" asp-controller="Events" asp-action="Index">Новини и Събития</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="" asp-controller="ForestryInstitutions" asp-action="Index">Институции</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="" asp-controller="PurposeOfCutOffs" asp-action="Index">Регулации</a>
                    </li>
                </ul>
            </div>
        </div>
        <partial name="_LoginPartial" />
    </nav>
</header>


@if (User.IsInRole("Admin") || User.IsInRole("Expert"))
{
    <header>
        <nav class="fill navbar navbar-expand-sm navbar-toggleable-sm navbar-light box-shadow">
            <div class="container-fluid">
                <img src="~/images/logo.jpg" alt="Logo Image" style="width:300px;height:70px;">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Начало</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Events" asp-action="Index">Новини и Събития</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="ForestryInstitutions" asp-action="Index">Институции</a>
                        </li>
                        <li>
                            <a class="nav-link text-light" asp-area="" asp-controller="UserRoles" asp-action="Index">Потребители</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-light" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Горски характеристики
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item nav-link" asp-area="" asp-controller="PurposeOfCutOffs" asp-action="Index">Регулации</a></li>
                                <li><a class="dropdown-item nav-link" asp-area="" asp-controller="TypeOfTimbers" asp-action="Index">Видове сечи</a></li>
                                <li><a class="dropdown-item nav-link" asp-area="" asp-controller="TypeOfWoods" asp-action="Index">Дървесни видове</a></li>
                                <li><a class="dropdown-item nav-link" asp-area="" asp-controller="CategoryOfTimbers" asp-action="Index">Категория дъвесина</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
            <partial name="_LoginPartial" />
        </nav>
    </header>
}
<div>
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)

</html>